stages:
  - test

variables:
  PYTHONPATH: "./src"

test:
  stage: test
  image: python:3.13
  script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - pytest -q
  only:
    - branches
    - merge_requests