classification_config:
  keyword_matching:
    allow_stemming: true
    case_sensitive: false
    exact_match_only: false
  metadata_extraction:
    enabled: true
    max_metadata_count: 10
  ml_assistance:
    enabled: true
    fallback_to_rules: true
    model_path: models/offline/document_classifier
  text_sampling:
    min_section_length: 200
    sample_sections: 3
    sample_size: 5000

# 查询意图路由覆盖（新增）：
# 针对不同文档类型，为“需检索/直接回答/调用工具/闲聊”提供偏好与动作建议，
# 以便上层意图路由在选择策略时参考，达到降本增效与提升体验。
intent_routing_overrides:
  technical_doc:
    tool_preference:
      triggers:
        keywords: [API, 接口, 调用, curl, HTTP, POST, GET, webhook]
        patterns: [".*调用.*接口.*", ".*API.*文档.*"]
      default_action: tool
      allowed_tools: ["direct_tool_call", "search_knowledge"]
      fallback_action: rag
    retrieval_preference:
      default_action: rag
      strategy_hint: "技术文档_具体细节查询"
      top_k: 8
  requirement_doc:
    retrieval_preference:
      default_action: rag
      strategy_hint: "需求文档_具体细节查询"
      top_k: 7
    direct_answer_preference:
      default_action: direct_answer
      preset_enabled: true
  academic_paper:
    overview_preference:
      default_action: rag
      strategy_hint: "学术论文_概述请求"
      top_k: 5
    citation_preference:
      default_action: rag
      strategy_hint: "学术论文_具体细节查询"
      top_k: 7
  multilingual_doc:
    overview_preference:
      default_action: rag
      strategy_hint: "多语言RAG_中英文查询"
      top_k: 12
  general:
    chitchat_preference:
      default_action: refuse_or_short_reply
      preset_reply: "我主要处理与文档和工具相关的问题。"
  report_doc:
    overview_preference:
      default_action: rag
      strategy_hint: "report_overview"
      top_k: 3
  meeting_minutes:
    retrieval_preference:
      default_action: rag
      strategy_hint: "meeting_minutes_action_items"
      top_k: 6
document_types:
- confidence_threshold: 0.75
  description: 包含学术研究内容的文档，通常有标题、摘要、引言、方法、结果、结论等结构
  file_extensions:
  - .pdf
  - .docx
  - .md
  id: academic_paper
  keywords:
  - 摘要
  - 引言
  - 方法
  - 实验
  - 结果
  - 结论
  - 参考文献
  - reference
  - abstract
  - introduction
  - method
  - experiment
  - result
  - conclusion
  metadata_keys:
  - doi
  - author
  - publication_date
  - journal
  - conference
  min_keywords_match: 3
  name: 学术论文
- confidence_threshold: 0.7
  description: 描述产品或项目需求的文档，通常包含功能需求、非功能需求等
  file_extensions:
  - .docx
  - .pdf
  - .md
  - .xlsx
  id: requirement_doc
  keywords:
  - 需求
  - shall
  - 必须
  - 功能
  - 性能
  - 接口
  - 约束
  - 用户故事
  - user story
  - requirement
  - function
  - performance
  - interface
  metadata_keys:
  - project_name
  - version
  - author
  - reviewer
  - approval_date
  min_keywords_match: 3
  name: 需求文档
- confidence_threshold: 0.65
  description: 虚构类文学作品，包含故事情节、人物对话等
  file_extensions:
  - .txt
  - .docx
  - .md
  - .pdf
  id: novel_story
  keywords:
  - 第一章
  - 第二章
  - 第一回
  - 第二回
  - 却说
  - 只见
  - 笑道
  - 想道
  - character
  - dialogue
  - chapter
  - scene
  metadata_keys:
  - title
  - author
  - publisher
  - publish_date
  - genre
  min_keywords_match: 2
  name: 小说故事
- confidence_threshold: 0.7
  description: 描述技术实现、架构、接口等内容的文档
  file_extensions:
  - .md
  - .pdf
  - .docx
  - .html
  id: technical_doc
  keywords:
  - 架构
  - 设计
  - 实现
  - 接口
  - API
  - 类
  - 函数
  - 模块
  - architecture
  - design
  - implementation
  - interface
  - class
  - function
  - module
  metadata_keys:
  - version
  - author
  - update_date
  - system_name
  - component_name
  min_keywords_match: 3
  name: 技术文档
- confidence_threshold: 0.8
  description: 具有法律效力的协议文档，包含条款、责任、义务等
  file_extensions:
  - .pdf
  - .docx
  id: contract_agreement
  keywords:
  - 合同
  - 协议
  - 条款
  - 甲方
  - 乙方
  - 责任
  - 义务
  - 权利
  - contract
  - agreement
  - clause
  - party a
  - party b
  - obligation
  - right
  metadata_keys:
  - contract_number
  - sign_date
  - effective_date
  - expiry_date
  - parties
  min_keywords_match: 3
  name: 合同协议
- confidence_threshold: 0.65
  description: 包含调查、分析、总结等内容的报告类文档
  file_extensions:
  - .pdf
  - .docx
  - .xlsx
  id: report_doc
  keywords:
  - 报告
  - 总结
  - 分析
  - 调查
  - 建议
  - 结论
  - report
  - summary
  - analysis
  - investigation
  - recommendation
  metadata_keys:
  - report_title
  - author
  - date
  - department
  - project
  min_keywords_match: 2
  name: 报告文档
- confidence_threshold: 0.75
  description: 记录会议内容、决议、行动项等的文档
  file_extensions:
  - .docx
  - .md
  - .txt
  id: meeting_minutes
  keywords:
  - 会议纪要
  - 参会人员
  - 议题
  - 决议
  - 行动项
  - 负责人
  - deadline
  - minutes
  - attendees
  - agenda
  - resolution
  - action item
  - responsible
  - due date
  metadata_keys:
  - meeting_title
  - date
  - location
  - chairperson
  - attendees
  min_keywords_match: 3
  name: 会议纪要
- confidence_threshold: 0.65
  description: 包含英文内容并可能需要跨语言处理的文档
  file_extensions:
  - .txt
  - .docx
  - .pdf
  id: multilingual_doc
  keywords:
  - Version
  - Release Date
  - TRS
  - Technical Reference Sheet
  - User Guide
  - Manual
  - Documentation
  - Specification
  - 参数
  - 功能
  - 系统
  - 配置
  - 说明
  metadata_keys:
  - version
  - release_date
  - language
  - author
  min_keywords_match: 2
  name: 多语言文档
