prompt_templates:
  default: "根据提供的上下文信息回答问题，确保回答准确、简洁。"
  summary: "请基于上下文生成简洁的概览，突出关键点。"
  technical_detail: "请提供明确的技术细节、参数说明与示例。"
  action_items: "请提取会议纪要中的所有行动项、负责人与截止日期，并清晰汇总。"

retrieval_strategies:
  hybrid:
    semantic_weight: 0.7
    keyword_weight: 0.3
    rerank: true
  semantic_only:
    semantic_weight: 1.0
    keyword_weight: 0.0
    rerank: true
  keyword_only:
    semantic_weight: 0.0
    keyword_weight: 1.0
    rerank: false

strategies:
  general_specific_detail:
    top_k: 5
    score_threshold: 0.6
    embedding_model: default
    reranker_weight: 0.4
    prompt_template: technical_detail
    retrieval_type: hybrid
    diversity_factor: 0.2
    chunk_overlap: 0.15
    context_window: 12000

  general_overview:
    top_k: 3
    score_threshold: 0.5
    embedding_model: default
    reranker_weight: 0.3
    prompt_template: summary
    retrieval_type: semantic_only
    diversity_factor: 0.4
    chunk_overlap: 0.2
    context_window: 10000

  technical_specific_detail:
    top_k: 6
    score_threshold: 0.65
    embedding_model: default
    reranker_weight: 0.45
    prompt_template: technical_detail
    retrieval_type: hybrid
    diversity_factor: 0.25
    chunk_overlap: 0.2
    context_window: 12000

  technical_general:
    top_k: 4
    score_threshold: 0.55
    embedding_model: default
    reranker_weight: 0.35
    prompt_template: summary
    retrieval_type: semantic_only
    diversity_factor: 0.35
    chunk_overlap: 0.15
    context_window: 10000

  multilingual_query:
    top_k: 4
    score_threshold: 0.5
    embedding_model: multilingual
    reranker_weight: 0.3
    prompt_template: default
    retrieval_type: hybrid
    diversity_factor: 0.3
    chunk_overlap: 0.2
    context_window: 10000

  contract_specific_detail:
    top_k: 6
    score_threshold: 0.6
    embedding_model: default
    reranker_weight: 0.4
    prompt_template: default
    retrieval_type: hybrid
    diversity_factor: 0.25
    chunk_overlap: 0.2
    context_window: 12000

  requirement_overview:
    top_k: 3
    score_threshold: 0.5
    embedding_model: default
    reranker_weight: 0.3
    prompt_template: summary
    retrieval_type: semantic_only
    diversity_factor: 0.35
    chunk_overlap: 0.15
    context_window: 10000

  report_overview:
    top_k: 3
    score_threshold: 0.5
    embedding_model: default
    reranker_weight: 0.3
    prompt_template: summary
    retrieval_type: semantic_only
    diversity_factor: 0.35
    chunk_overlap: 0.15
    context_window: 10000

  meeting_minutes_action_items:
    top_k: 5
    score_threshold: 0.55
    embedding_model: default
    reranker_weight: 0.4
    prompt_template: action_items
    retrieval_type: hybrid
    diversity_factor: 0.25
    chunk_overlap: 0.2
    context_window: 12000

strategy_hints:
  fast_summary: general_overview
  deep_retrieval: general_specific_detail
  tech_detail: technical_specific_detail
  tech_overview: technical_general
  multilingual: multilingual_query
  contract_detail: contract_specific_detail
  requirement_overview: requirement_overview
  report_overview: report_overview
  meeting_minutes_action_items: meeting_minutes_action_items